# Generated by Django 5.0.4 on 2024-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('language', models.CharField(max_length=100)),
                ('corpus_date', models.CharField(max_length=100)),
                ('corpus_id', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'corpus_data',
            },
        ),
    ]
